version: "3.7"
services:
  postgres:
    container_name: fab-postgres
    image: postgres:10
    restart: unless-stopped
    env_file: .env
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: pguserpassword
      POSTGRES_USER: pguser
    ports:
      - 5432:5432
